### ISSUE TITLE
How to configure the port?

### ISSUE THREAD

**Issue by MatthiasLohr** [mozilla-iot/gateway-docker#13]
Hello,

can I pass parameters or modify a configuration file in that way, that the things webinterface listens on other ports than 8080 etc.? On the machine where I want to run this Docker image is already a service listening on port 8080 - and when running it with --net=host the port parameters have no effect.

Any solution for that?

Best regards
Matthias

**Comment by mrstegeman** [comment]
We have a local config file, but it's apparently not even being used. After mozilla-iot/gateway#1502 is merged (and I build a new image), you can edit `/path/to/shared/data/config/local.json` as such:

```json
{
  "ports": {
    "https": 443,
    "http": 80
  }
}
```
