### ISSUE TITLE
ZigBee USB Device

### ISSUE THREAD

**Issue by who93** [mozilla-iot/gateway-docker#14]
Hi,
I was able to run the Mozilla-Gateway without docker and now I am switching to the docker version. Inside docker, I get following error message "Failed to load zigbee-adapter - No Digi port found". Do I need to configure something that my container has access to the zigbee Digi Stick?

sudo docker run -d --device=/dev/ttyUSB0 --rm -v /home/user/gateway:/home/node/.mozilla-iot --net=host --name mozilla-iot-gateway mozillaiot/gateway:latest

Cheers

**Comment by mrstegeman** [comment]
@dhylands Do you have any tips for serial port debugging?

**Comment by dhylands** [comment]
The zigbee adapter uses the SerialPort module, which internally uses udev to detect serial ports. The error indicates that the container isn't seeing the dongle, which presumably means that something needs to be done to allow it to do so.

If you cd into the gateway/tools directory and run the following commands:
```
npm install sserialport
node ./list_ports.js
```
then it should list of the serial ports which can be seen. If you don't see the Digi dongle using list_ports.js, then the zigbee adapter won't be able to see it either.

So you need to adjust whatever it is that's required with docker to allow it to see the usb dongle.

**Comment by who93** [comment]
The device is correctly showing up in the container:
`lsusb: Bus 001 Device 004: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC`
But with ./list_ports.js not: 
```
Serial Device found @ /dev/ttyUSB0
Serial Device found @ /dev/ttyS0
Serial Device found @ /dev/ttyS1
Serial Device found @ /dev/ttyS2
Serial Device found @ /dev/ttyS3
```
On my host machine I see following:
```
USB Serial Device 0403:6001 Vendor: Digi found @ /dev/ttyUSB0
Serial Device found @ /dev/ttyS0
Serial Device found @ /dev/ttyS1
Serial Device found @ /dev/ttyS2
Serial Device found @ /dev/ttyS3
```
Since lsusb detects the stick in the container, I think its not an issue of docker. What does list_ports.js require to detect devices?

**Comment by dhylands** [comment]
It looks like its showing up as a serial port, but that the USB information isn't making it through.

There is a script called udevadm in gateway/tools which you can copy to someplace in the PATH and see if list_ports.js shows the USB information. usbdevadm was created for OpenWRT which doesn't have udev support.

The node SerialPort module calls udevadm internally.

**Comment by mrstegeman** [comment]
@mcbridematt I'm glad you got this working! Please submit a PR and I will happily merge and build a new image.

**Comment by who93** [comment]
thanks @mcbridematt !
I tried your fix and the device is found: `USB Serial Device 0403:6001 Vendor: Digi found @ /dev/ttyUSB*`
However, it should be /dev/ttyUSB0 and not /dev/ttyUSB*, because of this, the gateway shows me:  ```
Opening serial port /dev/ttyUSB*
SerialPort open err = Error: Error: No such file or directory, cannot open /dev/ttyUSB*
```
Any ideas on that?

**Comment by who93** [comment]
Thanks for the merge. However, this was not solving the issue. After freshly building and starting the docker container, I still get this problem:
```
zigbee: Opening serial port /dev/ttyUSB*
zigbee: SerialPort open err = Error: Error: No such file or directory, cannot open /dev/ttyUSB*
```

**Comment by mrstegeman** [comment]
@mcbridematt What docker argument are you using to share in your device node?

**Comment by mcbridematt** [comment]
I'm using --privileged, which shares the entire /dev tree.

```docker create --privileged --net=host  --name=mozilla-iot-gateway-dev ...```

Using --device would be safer but this would not give you access to the /dev/bus/usb and other things required to enumerate USB devices, hence I suggested the zigbee adapter have a way to specify a device manually.
