### ISSUE TITLE
Raspberry Pi reboots when trying to pull the image

### ISSUE THREAD

**Issue by fussballball** [mozilla-iot/gateway-docker#16]
Upon pulling the image the raspberry Pi reboots. Clean install, nothing else done. Logging via SSH the connection got closed, to figure the problem out I hooked it up to a desktop. Turns out, it reboots.

Excerpt from cat /etc/os-release Output:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
VERSION_ID="9"
ID=raspbian
ID_LIKE=debian

docker --version
Docker version 18.09.0, build 4d60db4

docker run hello-world does give the expected output (and does not reboot), docker pull mozillaiot/gateway:arm results in the following output:

    Unable to find image 'mozillaiot/gateway:arm' locally  
    arm: Pulling from mozillaiot/gateway  
    773085009f9c: Pulling fs layer  
    15973945ecf5: Pulling fs layer  
    4e25b539801e: Pulling fs layer  
    a84cdb78f6b0: Waiting  
    0c9b8944dc77: Waiting  
    e5d5b177fb91: Waiting  
    b607d4912e2c: Waiting  
    f0483e81618e: Waiting  
    a1e85dbd8e2c: Waiting  
    e01229de56d3: Waiting  
    9dd67d3b7895: Waiting  
    e983d85a8d9c: Waiting  
    00e328c139d4: Waiting  
    7ae91a156a8c: Waiting  
    Connection reset by 192.168.X.ZZZ port 22.  

Then the raspberry reboots.

Still trying to figure out if it is my bad (I am assuming not, since it is a clean install of the OS), and if others can reproduce the issue.

Best and thanks a lot!

P.S: cloning the git repository and then trying to build it results in the same behavior. The Code used was this (/path/to/shared/data was changed obviously): 
git clone https://github.com/mozilla-iot/gateway-docker
cd gateway-docker
docker build -t gateway .
docker run \
    -d \
    --rm \
    -v /path/to/shared/data:/home/node/.mozilla-iot \
    --net=host \
    --name mozilla-iot-gateway \
    gateway

**Comment by mrstegeman** [comment]
Is it possible that you're running out of space on your SD card? The Docker image is ~1.6 GB.

**Comment by fussballball** [comment]
That's a good guess, but not really. It's a 32GB SD Card with only raspbian and docker installed. I think about 27GB are left. I made a clean reset on another SD card, with the same result. Also, the reboot happens almost immediately (on a normal PC I would say it blue-screens, but on the raspberry there's no blue screen and no error message - it just reboots)

**Comment by mrstegeman** [comment]
The only time I’ve seen these issues are with either a bad RPi or a bad power adapter.

@dhylands any other ideas?

**Comment by fussballball** [comment]
Power adapter seems to have been the issue. Sorry for opening an issue for that - I genuinely thought (since I bought a recommended power adapter, though from an online forum recommended) that that would not be an issue. So far it also hadn't been. Thanks for the hint.

**Comment by mrstegeman** [comment]
No problem! Glad you got it figured out.
