### ISSUE TITLE
Permission errors with volumes created by `docker volume`

### ISSUE THREAD

**Issue by jimmycuadra** [mozilla-iot/gateway-docker#19]
I'm running into permissions errors when bind mounting a volume created with `docker volume`:

```
$ docker volume create my-docker-volume
$ docker run -d -p 8080:8080 -p 4443:4443 -v my-docker-volume:/home/node/.mozilla-iot --name mozilla-iot-gateway mozillaiot/gateway
$ docker logs mozilla-iot-gateway
+ MOZIOT_HOME=/home/node/.mozilla-iot
+ args=
+ start_task=start
+ is_docker_container
+ '[' -f /.dockerenv ']'
+ return 0
+ mkdir -p /home/node/.mozilla-iot/log
mkdir: cannot create directory '/home/node/.mozilla-iot/log': Permission denied
```
That error just gets repeated forever.

If I create a directory on my machine directly and bind mount that, everything works as expected, so it seems to be specific to Docker-managed volumes.

**Comment by mrstegeman** [comment]
Thanks for reporting! I'm getting ready to push the 0.8.1 release, this fix is included.
