### ISSUE TITLE
[Feature Request] Automated build and push for dockerfiles to dockerhub

### ISSUE THREAD

**Issue by kmehant** [mozilla-iot/gateway-docker#23]
### Context
Shall we implement a CI pipeline to automatically build Dockerfiles and push the images to the docker hub whenever changes are made to the present Dockerfiles?

**Comment by kmehant** [comment]
@mrstegeman Can I integrate a Travis CI to this project?

**Comment by mrstegeman** [comment]
I'd rather not. I would prefer to manually verify changes to the Dockerfile and version things appropriately.
