### ISSUE TITLE
Failed to generate certificate

### ISSUE THREAD

**Issue by Kombustor** [mozilla-iot/gateway-docker#26]
I'm using the image with the recommended docker-compose configuration. When trying to register the subdomain, the error "Error issuing certificate. Please try again." appears (but the confirmation email is being sent). The following error is printed to the log:
```
webthings-gateway    | 2019-11-17 16:32:04.711 INFO   : Sent subscription to registration server
webthings-gateway    | 2019-11-17 16:32:29.900 ERROR  : Failed to generate certificate: Error: Could not resolve URL for API resource: "newAccount"
webthings-gateway    |     at HttpClient.getResourceUrl (/home/node/mozilla-iot/gateway/node_modules/acme-client/src/http.js:132:19)
webthings-gateway    |     at <anonymous>
webthings-gateway    |     at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by mrstegeman** [comment]
It seems like your Docker container was not able to do DNS resolution for the Let’s Encrypt server. Is it possible you have something misconfigured in the network settings?
