### ISSUE TITLE
Great! I'm rebuilding the Docker images and will push to Docker Hub shortly.

### ISSUE THREAD

**Issue by DoctorWho8** [mozilla-iot/gateway-docker#28]
Great! I'm rebuilding the Docker images and will push to Docker Hub shortly.

_Originally posted by @mrstegeman in https://github.com/mozilla-iot/gateway-docker/issues/24#issuecomment-557306457_

I have a question regarding a Docker Image for the Raspberry Pi projects. How would I be able to properly make use of one? The Documentation is a bit murky in spots.

**Comment by mrstegeman** [comment]
* Step 1, install Docker on the RPi: https://www.raspberrypi.org/blog/docker-comes-to-raspberry-pi/
* Step 2 (optional), add yourself to the `docker` group:
  ```sh
  sudo usermod -aG docker pi
  ```
  You must log out and log back in after doing this.
* Step 3, run container: https://github.com/mozilla-iot/gateway-docker/blob/master/README.md#arm-eg-raspberry-pi
