### ISSUE TITLE
Synology Gui walkthrough

### ISSUE THREAD

**Issue by Arzachena** [mozilla-iot/gateway-docker#35]
Prompted by mrstegeman https://discourse.mozilla.org/t/too-many-certificates-already-issued/51534/3, I have written a walkthrough which uses the Synology Docker Gui and does not require SSH access. https://github.com/Arzachena/Mozilla-iot-gateway-on-synology/wiki
Now I don't know what to do with it. Could it be useful to some people? If yes, should I move it somewhere or what?
Clearly, the Note: "You may need to replace both occurrences of ttyACM0 with ttyACM0" is a weakness. It would be better if it could clarify which dongle brands need ttyACM0 and which need ttyACM0.

**Comment by mrstegeman** [comment]
Thank you! I've started a wiki, including this content, here: https://github.com/mozilla-iot/gateway-docker/wiki
