### ISSUE TITLE
Changing the Moz://a dashboard interface.

### ISSUE THREAD

**Issue by N4SIRODDIN3** [mozilla-iot/gateway-docker#41]
# Hi,
Is it possible to change the M dashboard background from blue to custom images?
Thanks in advance.

**Comment by mrstegeman** [comment]
You could [create an extension add-on](https://github.com/mozilla-iot/wiki/wiki#general-1) to load custom CSS and such.

**Comment by N4SIRODDIN3** [comment]
Sorry for my poor response time.
Thanks for your help.
