### ISSUE TITLE
Cannot run arduino CLI in container on Pi 4b

### ISSUE THREAD

**Issue by tatemz** [mozilla-iot/gateway-docker#42]
I'm attempting to use the [Candle-manager-addon](https://github.com/createcandle/Candle-manager-addon), which uses the `arduino-cli` to manage plugged in arduinos.

The Candle manager addon comes packaged with an `arduino-cli` that can run natively on my Raspberry Pi 4b, but that cannot be run on my Raspberry Pi 4b using the `mozillaiot/gateway` Docker image.

Below is output from my attempt at running the cli from the Raspberry pi:

```
pi@raspberrypi:/ $ uname -s && uname -m
Linux
armv7l

pi@raspberrypi:/ $ /home/pi/Development/iot/data/addons/Candle-manager-addon/arduino-cli/linux-arm/arduino-cli version
arduino-cli Version: 0.9.0 Commit: e4d02b4
```

Below is output from my attempt at running the cli from inside the container: 
(Host volume is mapped using `-v /home/pi/Development/iot/data:/home/node/.mozilla-iot`).

```
pi@raspberrypi:/ $ docker exec -it webthings-gateway sh

# uname -s && uname -m
Linux
armv7l

# ls -lha /home/node/.mozilla-iot/addons/Candle-manager-addon/arduino-cli/linux-arm/arduino-cli
-rwxr-xr-x 1 node node 14M Jul 18 08:32 /home/node/.mozilla-iot/addons/Candle-manager-addon/arduino-cli/linux-arm/arduino-cli

# /home/node/.mozilla-iot/addons/Candle-manager-addon/arduino-cli/linux-arm/arduino-cli version
sh: 1: /home/node/.mozilla-iot/addons/Candle-manager-addon/arduino-cli/linux-arm/arduino-cli: not found
```

As a note, I am opting to run the gateway in a docker container so that I can use my Pi for multiple purposes (as a desktop, Pi-Hole, and iOT Gateway) so using the Pi iOT Gateway image is not a preferred solution.

**Comment by tatemz** [comment]
After looking into it further. It is likely a problem with the arduino-cli that is installed with the addon. I got around this issue, but overriding the cli tool within the addon using the binary from https://arduino.github.io/arduino-cli/installation.

**Comment by mrstegeman** [comment]
I’m glad you got it working, but can I suggest filing an issue against the add-on: https://github.com/createcandle/Candle-manager-addon

**Comment by tatemz** [comment]
Ya will do as soon as I get a clean workaround script :+1:
