### ISSUE TITLE
Docker Hub releases do not have tags with associated mozilla-iot/gateway versions

### ISSUE THREAD

**Issue by Alberts00** [mozilla-iot/gateway-docker#6]
Docker is built and only has latest tag, during the building of image a git clone is issued and the latest commits from mozilla-iot/gateway master branch are cloned. This might contain newer, possibly breaking, features which are not in the latest release.

To improve stability it would be wise to match the Docker Hub releases with stable mozilla-iot/gateway releases via tagging. To lower the required maintenance of Docker images this process could be automated by CI server.

**Comment by mrstegeman** [comment]
@Alberts00 The latest (and only) release in Docker Hub is actually identical to the 0.4.0 gateway release. However, I do agree with you. I will tag that release and all releases moving forward accordingly.

**Comment by mrstegeman** [comment]
Tagged.

https://hub.docker.com/r/mozillaiot/gateway/tags/
