### ISSUE TITLE
openzwave not available - zwave adapter non-functional.

### ISSUE THREAD

**Issue by RoboPhred** [mozilla-iot/gateway-docker#8]
The arm container does not come with openzwave installed, resulting in the failure of the zwave plugin:

```
2018-07-15 19:52:01.244 Loading add-on: zwave-adapter
2018-07-15 19:52:02.036 zwave: Opening database: /home/node/.mozilla-iot/config/db.sqlite3
2018-07-15 19:52:02.078 zwave: Loading add-on for zwave-adapter from /home/node/.mozilla-iot/addons/zwave-adapter
2018-07-15 19:52:02.485 zwave: Failed to load zwave-adapter - Failed to load openzwave-shared: Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory
2018-07-15 19:52:02.500 Plugin: zwave-adapter died, code = 100 NOT restarting...
```

I was able to install it into the running container with docker exec with reasonable success.  I figure it's a common protocol, so it might be worth including in this container.

**Comment by dhylands** [comment]
@mrstegeman who is most familiar with the docker stuff just went on parental leave for a few weeks (six IIRC). Where did you install the docker container from?

There is a wik page which describes how to install the openzwave libraries:
https://github.com/mozilla-iot/wiki/wiki/Installing-OpenZWave

**Comment by mrstegeman** [comment]
The image should have `libopenzwave` installed, but it may be incompatible with the Z-Wave adapter.

See: https://github.com/mozilla-iot/gateway-docker/blob/master/Dockerfile#L17

That may need to be replaced with the the steps @dhylands posted above.

**Comment by dhylands** [comment]
It's interesting that its complaining specifically about libopenzwave.so-1.4 which ,means that it found a symlink for libopenzwave.so and that symlink is supposed to point to a libopenzwave.so.X.Y. The Dockerfile references 1.5 so maybe there's just a stale symlink someplace?

**Comment by RoboPhred** [comment]
I am using an Aeon Labs Z-Stick (older generation?).  I can see its model and vendor ID match up to the first entry in the adapters list, so the stick isn't (this) problem.

The docker image came down from the docker hub: `mozillaiot/gateway:arm`.  Note particularly this is the arm build, running on a raspberry pi.

I was able to fix this issue by following the 'Installing OpenZWave' steps inside a shell in the container, which seemed to solve it.  Once the installation completed, disabling / enabling the adapter plugin showed that it successfully loaded the openzwave lib and the OZW_ log appeared.

Despite that success, I immediately hit two others: udev not installed (no udevadm for serial discoverability), and post-install udev not picking up my device attached with the `docker run --device` option.  The first is probably a real issue; I didn't get around to tracking down the second.  I will make other issues for those once this one gets resolved, so I am working from a consistent / supported base.

**Comment by mrstegeman** [comment]
@RoboPhred Yeah, I knew there were going to be additional steps to take if adapters with hardware devices were used, but I never had the time to actually work through those.

I would welcome patches if you manage to get it working, but I won't be able to look at it myself for several weeks. Alternatively, you could run natively on the RPi. You don't have to use our prebuilt image, you can build and run the gateway yourself.

**Comment by RoboPhred** [comment]
Thanks for the support, I should be able to keep working on this and submit a patch.

**Comment by RoboPhred** [comment]
I cant seem to find any references to the 1.4 version of openzwave anywhere, so I am not sure where its getting the info from.

`find / -name libopenzwave*` results in:
```
/usr/lib/arm-linux-gnueabihf/libopenzwave.so.1.5
/usr/lib/arm-linux-gnueabihf/libopenzwave.so
```

The libopenzwave.so symlinks correctly:
```
ls -la /usr/lib/arm-linux-gnueabihf/libopenzwave.so
lrwxrwxrwx 1 root root 19 Dec 23  2016 /usr/lib/arm-linux-gnueabihf/libopenzwave.so -> libopenzwave.so.1.5
```

This should be being used, as that path is known to ldconfig:
```
ldconfig -v 2>/dev/null | grep -v ^$'\t'
/lib/arm-linux-gnueabihf:
/usr/lib/arm-linux-gnueabihf:
/usr/local/lib:
/lib:
/usr/lib:
```

At this point, I am up against the edge of my knowledge.  I have no idea why it cannot find the installed version.  I could produce a patch that instructs the dockerfile to download and install openzwave from the git repo, but that would just be working around the problem.

Can you suggest any further action I could take to investigate this?

**Comment by dhylands** [comment]
The reference is probably coming from openzwave_shared.node.

That file should be located in ~/.mozilla-iot/addons/zwave-adapter/node_modules/openzwave-shared/build/Release

On my linux build machine if I run ldd I see the following:
```
511 >ldd openzwave_shared.node 
	linux-vdso.so.1 (0x00007ffef6146000)
	libopenzwave.so.1.4 => /usr/local/lib/libopenzwave.so.1.4 (0x00007f5e82136000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5e81da8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5e81a0a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5e817eb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e813fa000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f5e811dc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5e80fc4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5e8267f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5e80dbc000)
```
That tells me that openzwave_shared.node is referencing libopenzwave.so.1.4.

You might be able to create a symlink for libopenzwave.so.1.4 that points to libopenzwave.so.1.5 as a temporary workaround.

**Comment by mrstegeman** [comment]
@RoboPhred Everything you need should now be in the container. I'm able to at least start up the Z-Wave, Zigbee, and Serial add-ons, all of which require udev. You'll probably have to share in the device node from `/dev` and potentially run your container as `--privileged`. If you get things working, let me know and we can update the README.

**Comment by laibulle** [comment]
Any update. I still have the issue

```
2018-10-17 21:02:51.115 zwave: Loading add-on for zwave-adapter from /home/node/.mozilla-iot/addons/zwave-adapter
2018-10-17 21:02:51.656 zwave: Failed to load zwave-adapter - Unable to find ZWave adapter
2018-10-17 21:02:52.079 Plugin: zwave-adapter died, code = 100 NOT restarting...
```

**Comment by mrstegeman** [comment]
`Failed to load zwave-adapter - Unable to find ZWave adapter`

That indicates to me that the adapter is not seeing the tty device. @dhylands would be of more use than me on this. I would guess that either those are not the correct device nodes, or that the permissions are off.

**Comment by dhylands** [comment]
That particular error means that the serial port enumeration failed (as opposed to the error "No ZWave port found" which means that the enumeration worked, but it just didn't find any zwave devices.

In the gateway/tools directory is a file called list_ports.js.

If you cd into the zwave-adapter directory (~/.mozilla-iot/addons/zwave-adapter) and copy the gateway/tools/list_ports.js file into the zwave-adapter directory and then run it. That uses the same code as the zwave-adapter and may give a better error message,
